### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-amazondash

### ISSUE THREAD

**Issue by komainu85** [KhaosT/homebridge-amazondash#19]
Installed home bridge, dash button and homebridge-amazondash per the instructions on my raspberry pi zero.

calling sudo homebridge as root is throwing the below exception. Any ideas?

root@raspberrypi:/usr/local/lib/node_modules/homebridge/devPlugins/homebridge-suncalc# sudo homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[5/31/2017, 4:46:21 PM] ====================
[5/31/2017, 4:46:21 PM] ERROR LOADING PLUGIN homebridge-amazondash:
[5/31/2017, 4:46:21 PM] Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[5/31/2017, 4:46:21 PM] ====================
[5/31/2017, 4:46:21 PM] No plugins found. See the README for information on installing plugins.
[5/31/2017, 4:46:21 PM] Loaded config.json with 0 accessories and 1 platforms.
[5/31/2017, 4:46:21 PM] ---
[5/31/2017, 4:46:21 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'AmazonDash' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by komainu85** [comment]
copied in the build folder from homebridge and that works. not a great fix though.

**Comment by scratchedguitar** [comment]
Hi Komainu85, could you explain exactly what you did?

I don't really understand how to do that.

**Comment by honkmaster** [comment]
Have the same error? A detailed description would be perfect.

**Comment by honkmaster** [comment]
@KhaosT Any help? Is this plugin dead?

**Comment by KhaosT** [comment]
`Error: Cannot find module './build/Release/pcap_binding'`
Please follow the readme and install `libpcap-dev` ¯\_(ツ)_/¯

**Comment by honkmaster** [comment]
```
$ apt-get install libpcap-dev
libpcap-dev is already the newest version.
```

I have it installed, nonetheless, I have this issue.

**Comment by KhaosT** [comment]
In that case can you post the full error log when you run homebridge?

**Comment by Sammy990** [comment]
Hi, having the same issue. Hope someone can help libcap-dev installed in the newest version.

Error Log:
2018-5-18 23:24:55] ERROR LOADING PLUGIN homebridge-amazondash:
[2018-5-18 23:24:55] Error: Cannot find module './build/Release/pcap_binding'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/homebridge-amazondash/node_modules/pcap/pcap.js:3:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[2018-5-18 23:24:55] ====================

**Comment by Sammy990** [comment]
@KhaosT do you have any Hit how to solve it? Or @komainu85 maybe you can explain what you exactly did?
Thanks

**Comment by TubadoG** [comment]
Sammy, were you ever able to get this running?  I have a suspicion that I've got either a permission problem or an install location problem, but I don't have enough experience to know how to debug this on my own.  I'm running this as a systemd service and libpcap-dev seems to be installed correctly etc...
Any support would be baller! 
thanks,
