### ISSUE TITLE
Error when plugin is installing

### ISSUE THREAD

**Issue by elkorleone** [KhaosT/homebridge-amazondash#31]
I cannot finish the installation of this plugin in the HomeBridge UI. It's installed as a docker, can it be the problem? this is the message:

/homebridge # npm install -g homebridge-amazondash

> socketwatcher@0.3.0 install /usr/local/lib/node_modules/homebridge-amazondash/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function 'static void SocketWatcher::Callback(uv_poll_t*, int, int)':
../socket_watcher.cpp:77:60: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:929:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/socketwatcher/build'

> pcap@2.0.0 install /usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [pcap_binding.target.mk:94: Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.34-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-26T08_14_31_409Z-debug.log

**Comment by elkorleone** [comment]
nothing?

**Comment by KhaosT** [comment]
fatal error: pcap/pcap.h: No such file or directory
#include <pcap/pcap.h>

Please follow the readme and install libpcap.

**Comment by elkorleone** [comment]
Its impossible to add a DashButton to your homebridge (docker)
Could you please share the codes to do that?
Homebridge is running perfectly with other modules 

Enviado desde mi iPhone

**Comment by byronavory** [comment]
Install Error - appears to be outdated pcap/pcap.h reference
----------------------------------------------------------------------------------
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-amazondash@latest


> pcap@3.1.0 install /usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:10: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [pcap_binding.target.mk:110: Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-amazondash/node_modules/pcap
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-18T23_16_19_100Z-debug.log

Command failed. Please review log for details.
