### ISSUE TITLE
no install possible...

### ISSUE THREAD

**Issue by platini76** [KhaosT/homebridge-amazondash#35]
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/mranney/node_pcap.git /var/homebridge/.npm/_cacache/tmp/git-clone-073cd943
npm ERR! /var/homebridge/.npm/_cacache/tmp/git-clone-073cd943/.git: Permesso negato
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/homebridge/.npm/_logs/2018-11-04T01_09_52_248Z-debug.log

**Comment by TubadoG** [comment]
Same problem for me... did you find a fix?

**Comment by platini76** [comment]
no sorry...

**Comment by TubadoG** [comment]
I'm getting the same errors that others have posted.  I have tried running as pi and as  root, I followed the ReadMe and confirmed that I have libpcap installed and up to date.  @KhaosT any thoughts would be very appreciated.

`root@raspberrypi:/# npm install -g homebridge-amazondash`
`ERR! code 128`
`ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/mranney/node_pcap.git /root/.npm/_cacache/tmp/git-clone-ee90020c`
`ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-ee90020c': Permission denied`
`ERR! `
`ERR! A complete log of this run can be found in:`
`ERR!     /root/.npm/_logs/2018-11-10T19_43_59_183Z-debug.log`

**Comment by TubadoG** [comment]
Okay, I got it to install!!

Needed to run in root and also use sudo.  (Scary, but it worked). From there, I got everything to install.  However; now, I can't get the plugin to load...  I'm not sure if perhaps the plugin isn't in the right location...?  Can you help me understand how to figure out where Homebridge is looking for the plugin?  Side note - I'm running the Homebridge service via the systemd method.
`systemctl start homebridge`

Error: The requested platform 'AmazonDash' was not registered by any plugin.
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Module._compile (module.js:635:30)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Object.Module._extensions..js (module.js:646:10)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Module.load (module.js:554:32)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at tryModuleLoad (module.js:497:12)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Function.Module._load (module.js:489:3)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at Function.Module.runMain (module.js:676:10)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at startup (bootstrap_node.js:187:16)
Nov 10 15:39:52 raspberrypi homebridge[2859]:     at bootstrap_node.js:608:3
