### ISSUE TITLE
Dash Button // No device to listen //  Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by timloehrs** [KhaosT/homebridge-amazondash#8]
Hey Guys, 
got the following problem on setting up my dash button on homebridge:

After installing the plugin, and updating the Config.json, I got two kind of errors - depending wether I start homebridge with or without sudo.

without sudo:
`Error: Error: No devices to listen
    at create_session (/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/index.js:16:15)
    at register (/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/index.js:29:24)
    at DashPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-amazondash/index.js:54:17)
    at emitNone (events.js:67:13)
    at API.emit (events.js:166:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

with sudo:
`*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2016-11-07 14:43:01] Loaded plugin: homebridge-amazondash
[2016-11-07 14:43:01] Registering platform 'homebridge-amazondash.AmazonDash'
[2016-11-07 14:43:01] ---
[2016-11-07 14:43:04] Loaded plugin: homebridge-philipshue
[2016-11-07 14:43:04] Registering platform 'homebridge-philipshue.PhilipsHue'
[2016-11-07 14:43:04] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:199
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:199:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:49:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)`

Homebridge itself seems to work, at least my iphone recognized it and connect it as a new device.

My Config file looks like this:
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
   
   "platforms":{
     "platform": "AmazonDash",
     "buttons": [
       {
         "name": "Dash Blue",
         "mac": "mac-adress-of-my-dash"
       }
     ]
   }
}`

**Comment by KhaosT** [comment]
This is strange, homebridge tries to read configuration file and then crashed because there is no username field. Are you sure you placed the ``config.json`` in the right place?

**Comment by timloehrs** [comment]
I guess so, everytime I changed the parameters in the config file to something strange, I got a complete error of homebridge. Once I undo this, it kind of loads normal again. 

this is the path: ~/.homebridge/config.json
